apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: word2pdf
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080 # Ensure this port is open in your EC2 security group
